
name: Deploy Service to Prod

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy_action.yml
    with:
      aws-region: eu-west-1
      aws-ecr-repo: cedar-server
      aws-image-name: prod-latest
      account-id: '606913846469'