
name: Deploy Service to Staging

on:
  push:
    branches:
      - staging

permissions:
  id-token: write
  contents: read

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy_action.yml
    with:
      aws-region: eu-west-1
      aws-ecr-repo: cedar-server
      aws-image-name: staging-latest
      account-id: '158244227699' 


