name: Dry Run - Cedar Lambda Platform

on:
  workflow_dispatch:

jobs:
  dry-run:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Environment
        run: |
          echo "Branch: ${GITHUB_REF#refs/heads/}"
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::348286729043:role/OIDC-assumeRole-GithubActions

      - name: Dry Run Validation
        run: |
          echo "✅ Successfully assumed role"
          aws sts get-caller-identity
